



//================
//try
//{
//    int x = 0; int y = 0;
//   // int x = 5 / 0; // This will throw a DivideByZeroException
//    //Console.WriteLine(x);
//   // throw new Exception();
//    throw new DivideByZeroException("This is a divide by zero exception.");

//}
//catch (DivideByZeroException ex)
//{
//    Console.WriteLine("Caught DivideByZeroException: " + ex.Message); // Specific exception handling
//}
//catch (NullReferenceException ex)
//{
//    Console.WriteLine("Caught NullReferenceException: " + ex.Message); // Specific exception handling
//}
//catch (Exception ex)
//{
//    Console.WriteLine("Caught Exception: " + ex.Message); // General exception handling
//}

